### ISSUE TITLE
compact passing test blocks

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1472] opened 2019-07-25 17:26 UTC
There's good reasons to keep blocks of tests/examples separate rather than stuffing them all into a single block. However, each block produces its own output, which can sometimes fill up the screen and forces the REPL interactions to the bottom of the screen. It'd be nice if passing blocks, at least, could be compacted, or even the entire testing report be compacted into a single larger block. (Teachers at BS:DS are requesting this.)

**Comment by jswrenn** [comment] 2019-07-25 17:27
Heh, I'm actually on my second day of implementing this. :)

**Comment by blerner** [comment] 2019-07-25 17:35
Duplicate of https://github.com/brownplt/code.pyret.org/issues/310, filed earlier today, plus this is a CPO issue, not a pyret-lang one.

**Closed by blerner** 2019-07-25 17:35 UTC
Labels: error-message
