### ISSUE TITLE
CPO needs to provide a way to view Unicode

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#675] opened 2016-03-16 17:36 UTC
```
data ITunesSong: song(name :: String, singer :: String, year :: Number) end
s1 :: Number = song("La Vie en Rose", "Édith Piaf", 1945)
```

This produces the singer's name as `"\u00C9dith Piaf"`, which is fine. But I don't see any way to get Pyret
to actually print É, which is essential.

**Comment by shriram** [comment] 2016-03-16 17:39
NB: Ben is aware of this and has said he'll get to it at some point. I think this is a good candidate for toggling, because both outputs are useful. But the default output should be the "pretty" version, not the unicode code. People trying to produce cutesy output are going to be pretty annoyed to have to keep clicking.

**Comment by blerner** [comment] 2016-03-16 18:03
This is a dupe of a bug @schanzer already filed: https://github.com/brownplt/code.pyret.org/issues/47.  Sorry for the noise.

**Closed by blerner** 2016-03-16 18:03 UTC
