### ISSUE TITLE
`examples` can't have doc string

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1155] opened 2017-09-06 11:34 UTC
```
examples "doc string":
  (0 * 0) is 0
  (-2 * -2) is 4
  (3 * 3) is 9
end
```
produces a syntax error at the colon on the first line. Replacing `examples` with `check` does not, nor does deleting the doc string.

I am writing into PAPL that an `examples` block can contain a doc string, so please make this happen. (-:

**Comment by blerner** [comment] 2017-09-06 12:12
Not a bug. This is already implemented, on horizon. It hasn't merged yet because horizon has performance issues right now.

**Comment by schanzer** [comment] 2017-11-04 03:15
This is now on CPO. OK to close?

**Closed** 2017-11-04 03:17 UTC
