### ISSUE TITLE
odd indentation

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#933] opened 2016-11-03 00:57 UTC
```
letrec
  odd = 
    lam(n): 
    if n == 0: false else: even(n - 1) end end,
  even = 
    lam(n): if n == 0: true else: odd(n - 1) end end:
  odd(11)
end
```
It is surprising to see the `if` indented at the same level as the `lam`.

**Comment by blerner** [comment] 2016-11-03 01:18
This is by design: any line with an `end` on it outdents to match where the end should go.  The formatting rule used is, either fit everything from the `lam` to the `end` on one line (in which case, like the `even` body, it looks fine), or put `lam` and `end` on their own lines with the body in the middle (in which case it will indent as expected).  This hybrid style is not supported.

**Comment by blerner** [comment] 2017-04-02 17:46
Going to close this as by-design, unless anyone objects again?

**Closed** 2017-06-18 05:29 UTC
