### ISSUE TITLE
confusion between `=` and `==`

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1354] opened 2018-06-30 18:14 UTC
Student writes
```
fun f(x):
  y == 5
  if x > y:
    "true"
  else:
    "false"
  end
end
```
and gets a "multiple expressions" error. I'd say it's pretty subtle to figure out what's wrong here if you aren't already familiar with the language.

**Comment by blerner** [comment] 2018-06-30 23:19
Dupe of #383?

**Comment by blerner** [comment] 2018-07-05 21:13
Closing as dupe; that issue has the same relevant commentary.

**Closed by blerner** 2018-07-05 21:13 UTC
