### ISSUE TITLE
"this code is not in the editor"

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1109] opened 2017-07-31 14:14 UTC
```
> .2
```
produces an error with a link that says
![image](https://user-images.githubusercontent.com/75030/28781391-e36247aa-75d7-11e7-8d0e-1b1e4f2eb2d5.png)
Mousing over this produces the really weird text, "this code is not in the editor".

_I_ can understand why it prints this, but to a user it makes no sense. Why are you telling me where it's _not_? A negative statement is such a strange thing to present. At the very least it should say something positive like "this error comes from a previous interaction" or say "the interaction window" or something like that.

Related to that, what is "the editor"? I'm editing in the REPL too, right? We should consistently use "definitions" and "interactions", not random phrases.

**Comment by blerner** [comment] 2017-07-31 14:15
Dupe of https://github.com/brownplt/code.pyret.org/issues/202.

**Closed by blerner** 2017-07-31 14:15 UTC

**Comment by jswrenn** [comment] 2017-07-31 19:06
As @blerner noted, seeing that message in this _particular_ context was the result of a (now fixed) bug. There are still situations in which this alert will, correctly, appear; e.g., when the snippeted code is not anywhere in the definitions or interactions history. Which brings me to the actual complaint here:

> Why are you telling me where it's not?

Because, unfortunately, we don't know much more about it. It _might_ be visible in another tab, but it might not. It's just not in the _current_ tab. The best solution may to remove the hyperlink styling on the srcloc altogether.

**Comment by shriram** [comment] 2017-07-31 19:15
Removing the hyperlink is far better than this kind of confusing pop-up!

**Comment by schanzer** [comment] 2020-03-17 03:11
@shriram I'm unable to reproduce this using any of the examples from this or the linked issues. OK to close?

**Comment by shriram** [comment] 2020-03-17 12:17
It's already closed.
