### ISSUE TITLE
Vars are seen as let-bindings in the REPL

### ISSUE THREAD

**Issue by hilmar-hoffmann** [brownplt/pyret-lang#755] opened 2016-07-08 11:12 UTC
Entering 

```
var w = 1
w := 2
```

in the CPO-REPL results in:

> The name w is defined as an identifier, but it is assigned as if it were a variable [...]

On horizon it is:

> An error occurred rendering the reason for this error [...]

**Comment by sorawee** [comment] 2016-07-08 17:41
I think this is a duplicate of #288

**Comment by hilmar-hoffmann** [comment] 2016-07-09 15:03
Oh, right, what about the Horizon-REPL though?

**Comment by sorawee** [comment] 2017-06-10 21:44
This is fixed on horizon REPL. Still not fixed on CPO. Let me close this as a duplicate of the issue I mentioned above.

**Closed by sorawee** 2017-06-10 21:44 UTC
