### ISSUE TITLE
can't meaningfully copy struct values

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#769] opened 2016-07-18 14:09 UTC
```
> [list: {foo: 1, bar: 2}, {foo: 3, bar: 4}]
```
The output, when _copied_ and pasted (say into an editor, or even into the REPL itself), comes out as
```
[list: {foo1bar2}{foo3bar4}]
```

(Separately, the rendering of the value is ugly as sin, but that's the least of its problems…)

**Comment by blerner** [comment] 2016-07-18 14:13
Duplicate of #683.  (Separately, complaining about ugliness is unhelpful.  What on earth would you like, given that it's exactly what the concrete syntax is?)

**Closed by blerner** 2016-07-18 14:13 UTC

**Comment by shriram** [comment] 2016-07-18 21:56
By rendering I meant the typeface choice.
