### ISSUE TITLE
accidental redefinition produces bad highlight

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#656] opened 2016-02-21 12:42 UTC
```
for map(e from [list: 1, 2, 3]):
  e + 3
end

map(lam(e): e + 3 end, [list: 1, 2, 3])

for index(n from 10):
  print(n)
end

index(lam(n): print(n) end, 10)

fun index(f, n):
  if n >= 0:
    nothing
  else:
    f(n)
    index(f, n - 1)
  end
end
```

produces the error

```
It looks like you've defined the name index twice, at
definitions: line 1, column 0definitions: line 13, column 0
You need to pick a different name for one of them.
```

where the first highlight selects the _whole_ program (note that L1C0 is not a definition of `index`).

However, the real problem is that `index` is built-in.

**Comment by blerner** [comment] 2016-03-19 14:46
Three comments:
* The underlying problem is a dupe of #678
* `index` is no longer a builtin
* the bad formatting of this message has been fixed

**Closed by blerner** 2016-03-19 14:46 UTC
