### ISSUE TITLE
my-gdrive doesn't work

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#565] opened 2015-09-07 20:05 UTC
It's been broken for several days already. We thought that it's a known issue but apparently it's not, so I decided to report it.

We definitely need this to be fixed when CS19 starts.

**Comment by jpolitz** [comment] 2015-09-07 21:03
Thanks, I thought the report from @awstlaur 's report was limited to him.

There _is_ a problem where if you use my-gdrive from the tab you connect to google from it requires a refresh.  However, aside from that I can't reproduce across several accounts and browsers.

Is it pervasive, can't be fixed by refresh, etc?

**Comment by sorawee** [comment] 2015-09-07 21:04
I am not sure, but it seems that we all (all CS19 TAs) experience this problem and no one can get it to work (including me).

**Comment by jpolitz** [comment] 2015-09-07 21:24
Jumped on a call with @sorawee and this magically worked.  There were some bad error messages related to mis-typing "my-grive", and some issues about what folder things were in, but now it seems to be "fine".  Keeping an eye out for if there is a worse underlying cause, though, that caused all the TAs to seem to have trouble.

**Comment by jpolitz** [comment] 2015-09-13 11:48
I'm closing this because I fixed the error that seemed to be causing it, and it's too broad on its own to be a useful issue.

**Closed** 2015-09-13 13:27 UTC
