### ISSUE TITLE
"show more" for lists?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1086] opened 2017-07-18 20:03 UTC
We have "show more" for tables. Can we have it for lists?

If someone types `roll-dice(10000)` in the REPL (or even at the end of definitions), they're going to wait a long time just for output to be printed.

I see no reason (other than historical convention) why lists should be printed in full when other vales, like tables, aren't.

**Comment by blerner** [comment] 2017-07-18 20:07
It's because we don't have delayed rendering implemented for any data types.  Tables are a *hack*, in that they don't obey the same snapshot-of-mutable-values semantics that lists do.  Having a lazy display of values is a long-term ask.

**Comment by schanzer** [comment] 2017-08-02 12:27
Isn't this essentially a dupe of #770 ? There are a lot of issues related to incremental rendering, which (if I understand the issue correctly) requires (a) the ability for the UI to call back into the Pyret runtime to render the next set set of values and (b) some kind of pseudo-thread-management so that this doesn't stomp on other things.

**Comment by schanzer** [comment] 2020-08-12 13:21
@shriram OK to close, since #770 subsumes it?

**Closed** 2020-08-12 14:48 UTC
