### ISSUE TITLE
big-bang doesn't nest properly

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#543] opened 2015-07-08 07:04 UTC
```
include world
include image
import image-structs as IS

big-bang(0, [list: 
    on-tick(lam(n):
        if num-modulo(n, 10) == 1:
          big-bang(n,
            [list:
              on-tick(lam(k): k - 1 end),
              stop-when(lam(k): k < 0 end),
              to-draw(lam(k): text(num-to-string(k), 20, IS.blue) end)
            ])
          n + 1
        else:
          n + 1 
        end
      end),
    to-draw(lam(n): text(num-to-string(n), 20, IS.violet-red) end),
    stop-when(lam(n): n > 100 end)])
```

**Comment by jpolitz** [comment] 2015-07-09 14:07
Note: the problem is with the `changingWorld` flag in world-lib.js, which is global for the library, rather than per-world, which won't let the inner world run while the outer world is paused waiting for the inner world to complete.

**Comment by sorawee** [comment] 2016-05-07 23:30
My plot lib needs this to be fixed, so I will take it.

**Comment by schanzer** [comment] 2016-07-17 01:09
@sorawee is this closed, now that the new world-lib has landed? Shriram's sample code runs fine on CPO now.

**Comment by jpolitz** [comment] 2016-07-17 02:14
Confirmed fixed.

**Comment by sorawee** [comment] 2016-07-17 02:15
@jpolitz  But you haven't merged https://github.com/brownplt/code.pyret.org/pull/77 yet. It worked without that PR?!?

**Closed by jpolitz** 2016-07-17 02:14 UTC

**Comment by jpolitz** [comment] 2016-07-17 02:16
Yes, the windows don't close is the only remaining thing that 77 would fix (though this example needs an `stop-when-close(true)` to work.

**Comment by sorawee** [comment] 2016-07-17 02:21
It's `close-when-stop` if I recall correctly ;)

Can you review and merge #77 so that we can really fix the issue? If I didn't misremember, when you click the close button without 77 it will close all windows. With 77, it closes only one. So technically the "big-bang doesn't nest properly" bug still exists in the CPO right now.
