### ISSUE TITLE
Compile errors in check blocks reported twice.

### ISSUE THREAD

**Issue by jswrenn** [brownplt/pyret-lang#618] opened 2016-01-06 15:40 UTC
Entering this into the definition window:

``` pyret
check:
  x
end
```

and running results in _two_ unbound id errors being reported rather than one.

**Comment by jpolitz** [comment] 2016-01-06 19:11
Pretty sure I caused this as a regression with 9a6ca6a2984ab6b95b5e97829c39b50d1258ee53, which doesn't omit check blocks, and ends up with those terms in two places as a result.  This will actually _only_ happen for unbound identifiers, I believe.  Thanks!

**Comment by jswrenn** [comment] 2016-11-21 19:18
This is still a bug.

**Comment by blerner** [comment] 2017-06-18 05:24
Dupe of #882.

**Closed by blerner** 2017-06-18 05:24 UTC
Labels: bug
