### ISSUE TITLE
check blocks print in reverse order

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#912] opened 2016-10-24 13:05 UTC
![image](https://cloud.githubusercontent.com/assets/75030/19646758/f28547e6-99c8-11e6-8e86-62ff99eb4d2d.png)

Shouldn't they print in the order they appear in the program? That's the order the programmer has in mind.

**Comment by blerner** [comment] 2016-10-24 13:06
This has been "fixed" six or seven times already. How does it keep regressing?

**Comment by jswrenn** [comment] 2016-10-24 17:37
> Shouldn't they print in the order they appear in the program? That's the order the programmer has in mind.

Check blocks are printed in program order, but unnamed check blocks are _numbered_ in reverse order. I think the past bugs were order-of-appearance, not order-of-naming.

I think the naming issue occurs [because of this use of `foldr`](https://github.com/brownplt/pyret-lang/blob/9decc74bee3ccb19eb6a43decd4e6d4e83666b31/src/arr/compiler/desugar-check.arr#L66).

**Comment by blerner** [comment] 2016-10-25 02:01
Welllllllll, the foldr has to be a foldr so that it preserves the ordering of the check blocks, or else they'll run in the wrong order.  I think the problem is more the counting a few lines up.  Maybe what we need is a `reverse(stmts.foldl(...))`?

**Comment by blerner** [comment] 2017-06-10 21:59
This is fixed in memo-jsast, and will be fixed on master when this branch merges.

**Closed** 2017-07-11 22:56 UTC
Labels: horizon-fixed
