### ISSUE TITLE
My code is producing an error message of an internal error

### ISSUE THREAD

**Issue by mmarkell** [brownplt/pyret-lang#1184] opened 2017-09-21 14:36 UTC
```
fun yay(l, keep):
  cases (List) l:
    | empty => empty
    | link(f, r) =>
      if keep:
        link(f * 2, yay(r, false))
      else:
        yay(r, true)
      end
  end
end

yay([list: 1,5,3,2,1], true)
```

**Comment by shriram** [comment] 2017-09-21 14:44
Hi there. I just tried this program and I'm unable to reproduce the error. 

Let me ask you to try something. Start code.pyret.org/editor and wait until everything is loaded (you should get a ">" prompt on the right). _After_ that, paste in the code, and run it. 

Do you still get the error?

**Comment by mmarkell** [comment] 2017-09-21 14:46
I just tried it, and you're right in that I can no longer produce the error. 

I'm slightly untrusting of that though, because before I ran this program, I had run several other programs without refreshing the page and they all worked fine...maybe there is something more nuanced going on? 

Either way, it works now, so thank you!

**Comment by schanzer** [comment] 2018-03-31 14:05
This was either fixed or not reproducible to begin with. Closing.

**Closed by schanzer** 2018-03-31 14:05 UTC
