### ISSUE TITLE
pyret tells me to report this as a bug?

### ISSUE THREAD

**Issue by Solomonz** [brownplt/pyret-lang#920] opened 2016-10-26 17:21 UTC
![image](https://cloud.githubusercontent.com/assets/8081782/19736824/f59f3a06-9b7e-11e6-965b-7edba99d1e74.png)

**Comment by jpolitz** [comment] 2016-10-26 17:39
Can you share your program with us?  Click Publish... at the top, and paste the link here (or email it to joe.politz@gmail.com if you don't want to share it publicly?)

**Comment by sorawee** [comment] 2016-10-31 20:25
I think the cause is from the `include` statement (see https://github.com/brownplt/pyret-lang/issues/740)

**Comment by schanzer** [comment] 2018-03-31 13:51
#740 is fixed now. @Solomonz Is this still an issue for the program that triggered the error?

**Comment by blerner** [comment] 2019-07-17 23:44
@jpolitz do you have any information on this, or should we close for lack of repro?

**Comment by jpolitz** [comment] 2019-07-18 00:40
I think we can safely close.

**Closed by jpolitz** 2019-07-18 00:40 UTC
