### ISSUE TITLE
mapping REPL values to definition locations

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#792] opened 2016-07-28 23:55 UTC
This is probably impossible, but I wonder if, when running a program, it's possible to somehow indicate which source expression a particular output value came from. For instance, if I write

```
a = 10
b = 5
a
b
```

The initial REPL will show

```
10
5
```

but it can be tedious (when you have lots of expressions) to figure out which thing produced the `10` and which the `5`.

**Comment by blerner** [comment] 2016-07-29 01:35
Not impossible, I've added the plumbing for this when I implemented tracing, from the outset. It's just in need of UI design.

**Comment by shriram** [comment] 2016-07-29 02:12
Is it possible to hack together a crappy UI for it for now?

**Comment by shriram** [comment] 2016-07-29 02:12
Maybe reuse some of @jswrenn's flashing interface?

**Comment by jpolitz** [comment] 2016-07-29 02:45
@shriram two things:

I'd like to resist building crappy interfaces "for now" in general. They have an annoying habit of sticking around and significantly impeding future progress.

Also, are you asking for something that prints the line where the variable is defined for the use of the variable? That won't happen anytime soon because we aren't going to start wrapping primitives like numbers.

If you want it to print the line where the variable is _used_ at the top level, that's much easier and what @blerner has already added support for.

**Comment by blerner** [comment] 2016-07-29 02:52
Stronger than that: right now, we deliberately have _no_ wrapping around the traced output, so that it "appears as if" it came from the program directly.  This was at your and @schanzer's request to make the flags look pretty.  (We had originally had it print out "Trace ##" next to each output, which you thought looked distracting, so we hid it.)  So there's no obvious place to "just print some text".

We also already have on-click behavior for most rich-rendered values (expanding small images, toggling fractions, expanding data and object values); we can't overload that trigger to also mean "navigate the source code", or we risk very real confusion.  So there's no obvious way to trigger jumping around in the code.

Together, then, there is no "crappy UI" we could throw together quickly that wouldn't violate other of your already existing design requests; this requires some thought and design.

**Comment by shriram** [comment] 2016-07-29 12:13
These are both great arguments. Thanks @jpolitz @blerner. Never hurts to document the reasons.

**Comment by shriram** [comment] 2016-07-29 12:13
@blerner I am now curious about what that "trace ##" output looks like again…

**Comment by blerner** [comment] 2017-06-18 05:05
For a program
```
include image
a = 10
b = 5
a
b
circle(10 * a, "solid", "red")
rectangle(b, a, "solid", "blue")
```
with the trace markers unhidden (this is a 1-line CSS change from what's already implemented and supported, not any new behavior), you get "Trace ##" in a smaller font, to the left of each traced output:
![image](https://user-images.githubusercontent.com/918464/27258190-1e9a5188-53c2-11e7-9537-9c549dda70e4.png)

**Comment by blerner** [comment] 2019-07-17 23:58
Dupe of #1201

**Closed by blerner** 2019-07-17 23:58 UTC
