### ISSUE TITLE
test failure box should be easier to expand

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#601] opened 2015-11-18 01:07 UTC
When a check box fails, the "click to expand" region is ONLY that text. Why not pretty much anywhere in the box, except maybe the edges in case someone wants to copy the text?

**Comment by blerner** [comment] 2015-12-12 21:55
This is more properly a CPO issue, right?

**Comment by blerner** [comment] 2016-03-19 15:52
Pinging @jswrenn

**Comment by jswrenn** [comment] 2017-09-08 13:26
Duplicate of https://github.com/brownplt/pyret-lang/issues/913.

**Closed** 2017-09-22 15:11 UTC
Labels: horizon-fixed
