### ISSUE TITLE
Code is indenting incorrectly

### ISSUE THREAD

**Issue by Emmay** [brownplt/pyret-lang#493] opened 2015-05-15 14:48 UTC
https://code.pyret.org/editor#share=0B9rKDmABYlJVN1o0TmdHVzhiQXM&v=v0.5r852

In this program (Parachute jumper), I have a line: 
```
| otherwise: I.put-image(AIRPLANE, 130, 420, I.put-image(JUMPER, c.x, c.y, BACKGROUND))
```
If I want to put the coordinates on their own line, like we suggest in Bootstrap, I don't get the "staircase" pattern I'm used to. If I hit enter after AIRPLANE, I expect 130, 420 to indent to be right underneath AIRPLANE, but instead they end up underneath otherwise, like so:
```
|otherwise: I.put-image(AIRPLANE, 
        130, 420, 
        I.put-image(JUMPER, 
          c.x, c.y, 
          BACKGROUND))
```

**Comment by blerner** [comment] 2015-05-15 15:05
This indentation is by design, and is consistent with how indentation of function arguments works everywhere else in Pyret.  It's *not* the same indentation as Racket: we don't align arguments under the first argument of the function call, because that tends to push the code way too far to the right margin, very quickly.  Every nesting construct (such as parentheses, or function blocks, or ask blocks, or clauses of an ask, or clauses of a data definition, etc.) increases the indentation by one level.  The reason your code looks odd is because you're starting your function call on the same line as the `otherwise:` keyword.  Whenever you have a right-hand side that's too long for one line, we'd suggest putting the line break after the colon, like this:

```
    | otherwise:
      I.put-image(AIRPLANE, 
        130, 420,
        I.put-image(JUMPER, c.x, c.y, BACKGROUND))
```
Now the nesting structure looks far clearer.  (Also, btw, note the space between the `|` and the `otherwise`, which is stylistically preferred, even if it's not syntactically required.)

**Comment by schanzer** [comment] 2015-05-16 15:26
Thanks for the explanation, @blerner . It's very helpful, and your re-formatting makes a lot more sense. :) 
Sanity-check: is the reason Emma's original code is indented by four chars because there are *two* nesting constructs introduced on the previous line (otherwise: and open-paren)?

Would it be reasonable of us to say "any Ask-then clause that doesn't fit entirely on one line should always begin on it's own"? This seems like a good hard-and-fast rule to use with our students.

**Comment by blerner** [comment] 2015-05-16 16:08
Exactly right.  

Also note that as a consequence of those two nesting constructs, if you add a line-break just after the colon, then `I.put-image(AIRPLANE,` indents...and the following line *doesn't have to move*, because it's already in the right position relative to the open function-argument-list.  Which means that even when your students don't follow the hard-and-fast rule you propose, and you help them fix it by adding the line breaks where we suggest them, the overall reformatting of their code is minimized to just the lines they break and not any subsequent ones.  (Contrast this with Racket, where choosing to break an argument list either before or after the first argument drastically affects the indentation of the subsequent lines of arguments.  The bouncing-around effect is really distracting...)

**Comment by blerner** [comment] 2015-06-23 14:20
closed as by design.

**Closed by blerner** 2015-06-23 14:20 UTC
