### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#1262] opened 2017-11-23 00:38 UTC
```
UNKNOWN VALUE:  
TypeError
columnNumber: 17
fileName: "https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js"
lineNumber: 247625
message: "next is undefined"
stack: "iter@https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:247625:17\ni@https://code.pyret.org/js/beforePyret.js:27:16404\na@https://code.pyret.org/js/beforePyret.js:27:16582\nn@https://code.pyret.org/js/beforePyret.js:27:16941\n"
__proto__: Object { stack: "", … }
```

Trace:

```
toReprHelp
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:245730:15
toReprFun
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:245757:20
reenterToReprFun
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:245819:20
toReprLoop
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:245837:14
toReprJS
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:245850:21
torepr/<
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:276245:18
run/kickoff<
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:247514:18
iter
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:247632:23
run
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:247731:7
runThunk
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:247893:14
callDeferred
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:276155:7
torepr
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:276244:16
log_torepr/<
https://d251z2akfyabv3.cloudfront.net/releases/a8e0ccc/cpo-main.jarr.gz.js:276263:18
_fulfilled
https://code.pyret.org/js/q.js:834:54
Promise.prototype.then/</<
https://code.pyret.org/js/q.js:863:30
Promise/promise.promiseDispatch
https://code.pyret.org/js/q.js:796:13
Promise.prototype.then/<
https://code.pyret.org/js/q.js:857:9
runSingle
https://code.pyret.org/js/q.js:137:13
flush
https://code.pyret.org/js/q.js:125:13
```

I can send the code to anyone that will take this issue privately (it's an assignment). Note that the code does not import anything at all: it's pretty much making stream of strings.

**Comment by blerner** [comment] 2017-11-23 00:44
Yikes -- that looks like a stack-safety issue.  Can you check (1) whether it's a browser-specific failure, (2) whether it fails in node also?

**Comment by blerner** [comment] 2019-07-17 23:11
Closing as not enough info to reproduce anymore...

**Closed by blerner** 2019-07-17 23:11 UTC
