### ISSUE TITLE
I've confused with fibonacci function using tail recursive.

### ISSUE THREAD

**Issue by cchuang0425** [brownplt/pyret-lang#1230] opened 2017-10-21 14:18 UTC
Hi,

I'm a Racket user, and learning the Pyret lang.

I've tried Pyret online and compiled by phase0, but I got wrong answer of fibonacci function using tail recusion:

```
#lang pyret

fun iter(a :: Number, b :: Number, count :: Number) -> Number:
  if count == 0:
    b
  else:
    iter((a + b), a, (count - 1))
  end
end


fun fib(n :: Number) -> Number:
  iter(1, 0, n)
where:
  fib(10) == 55
end

print(fib(10))
```

but its result is `512`.

How could I fix my program?

**Comment by sorawee** [comment] 2017-10-21 20:14
This is not a Pyret issue. Your `iter` function has a subtle mistake.

I don't know what you intend `iter` to be. Here's one way that it could be:

> iter(  $F_{n-1}$ , $F_{n}$ , 0 ) = $F_{n}$
> iter(  $F_{n-1}$ , $F_{n}$ , k ) = iter(  $F_{n}$ , $F_{n+1}$ , k - 1 )

This directly yields the following code:

```
fun iter(a :: Number, b :: Number, count :: Number) -> Number:
  if count == 0:
    b
  else:
    iter(b, a + b, count - 1)
  end
where:
  iter(1, 0, 0) is 0
  iter(0, 1, 0) is 1
  iter(1, 1, 0) is 1
  iter(1, 2, 0) is 2
  iter(2, 3, 0) is 3
  iter(3, 5, 0) is 5
  
  iter(1, 1, 3) is iter(1, 2, 2)
  iter(1, 2, 2) is iter(2, 3, 1)
  iter(2, 3, 1) is iter(3, 5, 0)
end
```

Now, we want

```
fib(0) = 0
fib(1) = 1
fib(2) = 1
fib(3) = 2
...
```

It's then natural to define `fib(-1) = fib(1) - fib(0) = 1` to be used as `a` in `iter`. Thus:

```
fun fib(n :: Number) -> Number:
  iter(1, 0, n)
where:
  fib(0) is 0
  fib(1) is 1
  fib(2) is 1
  fib(3) is 2
  fib(4) is 3
  fib(5) is 5
  fib(10) is 55
end
```

**Comment by sorawee** [comment] 2017-10-22 04:39
^Please forget the above. I think Pyret is buggy. @YanyanR tells me she tried on OCaml and it works. I tried in Haskell and Racket and it works too. Only Pyret gives 512...

**Comment by sorawee** [comment] 2017-10-22 05:14
Here's the compiled code (`show-compilation.jarr` is buggy right now and I can't run it, so I extract this from `.jarr` directly)

```
while(!R.isContinuation($ans43)) {
  switch($step38) {
  case 0: $step38 = 1;
  $al44 = L[5];
  var $ann$check53 = R._cA(L[5],$type$Number4,a40);
  if(R.isContinuation($ann$check53)) {
  $ans43 = $ann$check53;
  }
  break;
  case 1: $step38 = 2;
  $al44 = L[6];
  var $ann$check54 = R._cA(L[6],$type$Number4,b41);
  if(R.isContinuation($ann$check54)) {
  $ans43 = $ann$check54;
  }
  break;
  case 2: $step38 = 3;
  $al44 = L[7];
  var $ann$check55 = R._cA(L[7],$type$Number4,count42);
  if(R.isContinuation($ann$check55)) {
  $ans43 = $ann$check55;
  }
  break;
  case 3: $step38 = 4;
  $al44 = L[4];
  if(typeof(equal$always2.app) !== "function") {
  R.ffi.throwNonFunApp($al44,equal$always2);
  }
  $ans43 = equal$always2.app(count42,(0));
  break;
  case 4: var anf_if52 = $ans43;
  $step38 = R.checkPyretTrue(anf_if52)?5:6;
  break;
  case 5: $step38 = 9;
  $ans43 = b41;
  break;
  case 6: $step38 = 7;
  $al44 = L[3];
  // omitting isFunction check;
  $ans43 = _plus6.app(a40,b41);
  break;
  case 7: var anf_arg50 = $ans43;
  $step38 = 8;
  $al44 = L[2];
  // omitting isFunction check;
  $ans43 = _minus5.app(count42,(1));
  break;
  case 8: var anf_arg51 = $ans43;
  $step38 = 0;
  ++$elidedFrames46;
  if(--R.RUNGAS <= 0) {
  R.EXN_STACKHEIGHT = 0;
  $ans43 = R.mC();
  }
  a40 = anf_arg50;
  b41 = a40;
  count42 = anf_arg51;
  continue;
  case 9: var ann_check_temp47 = $ans43;
  $step38 = 10;
  $al44 = L[1];
  var $ann$check48 = R._cA(L[1],$type$Number4,ann_check_temp47);
  if(R.isContinuation($ann$check48)) {
  $ans43 = $ann$check48;
  }
  break;
  case 10: $step38 = 11;
  $ans43 = ann_check_temp47;
  break;
  case 11: ++R.GAS;
  return $ans43;
  default: R.ffi.throwSpinnakerError(L[0],$step38);
  }
}
```

Notice:

```
case 8: var anf_arg51 = $ans43;
  $step38 = 0;
  ++$elidedFrames46;
  if(--R.RUNGAS <= 0) {
  R.EXN_STACKHEIGHT = 0;
  $ans43 = R.mC();
  }
  a40 = anf_arg50;
  b41 = a40;
  count42 = anf_arg51;
  continue;
```

`b41` is set to `a40`, but this is intended to refer to `a40` _before_ the statement `a40 = anf_arg50;`.

**Comment by sorawee** [comment] 2017-10-22 05:21
I guess we gotta blame this change https://github.com/brownplt/pyret-lang/pull/1042/commits/e3df7014d826a3e9a8d3268b9111205c2ec3deda

That is, I am sorry, this is my fault :(

**Comment by sorawee** [comment] 2017-10-22 06:52
Thank you very much for the bug report!

**Comment by cchuang0425** [comment] 2017-10-22 12:57
Thank you for helping me.

**Comment by jpolitz** [comment] 2017-10-22 15:05
Not entirely your fault, @sorawee – I am somewhat embarrassed. I reviewed this code and didn't see the issue, _and I hammer on this exact issue when I teach tail calls in compilers_. I've given lectures about this issue twice now.

Whoops.

**Comment by blerner** [comment] 2017-10-22 16:16
Well, now we have a regression test to use on our students' compilers next time 😎

**Comment by blerner** [comment] 2017-10-22 16:23
This is an interesting bug: it comes about because we violated the key rule of anf, to only every assign to a variable once. In some sense it's not surprising that loop-carried dependencies cause problems here... Ah well, hindsight is 512/512, in this case. 😅

**Closed** 2017-10-30 16:08 UTC
Labels: bug
