### ISSUE TITLE
typed language incorrectly reverses order of tuples

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1249] opened 2017-11-10 01:40 UTC
```
fun f() -> {Number; String}:
  {3; "hi"}
end
```
This program type-checks fine. But when you run `f()` you get an error that the return annotation is not satisfied by `{"hi"; 3}`. This problem does not occur in untyped mode.

This really should have been caught by a test case. All it needs is a test that has distinct types in the tuple components, and a program that is run.

**Comment by blerner** [comment] 2017-11-10 01:58
This gets weirder.  If you run `f()` with the typechecker, you get an error in the console `UNKNOWN VALUE:  Object { name: "Number", pred: isPyretNumber(), refinement: false }`, called from within `toReprLoop`.  How could that happen?

Narrowed it down a lot further:
```
fun f() -> {Number; Number; Number}:
  {3; 4; 5}
end
f().{0}
```
the last line returns **5** in typechecking mode, but **3** in unchecked mode.

**Comment by blerner** [comment] 2017-11-10 02:01
Matthew, I think the problem is lines 503 and 505 of type-check.arr.  Specifically, you reverse `elts` and `t-elts` for purposes of ... notsurewhat ..., then use the resulting `exprs` to reconstruct the `s-tuple` on the subsequent line.

**Comment by shriram** [comment] 2017-11-10 02:07
My guess it's reversed in the type annotation too. After all, this does not produce a static type error! If it were reversed in one place and not the other, it would. So my guess is, this reversal is not useless but to match an invariant from elsewhere.

**Comment by sorawee** [comment] 2017-11-24 00:03
Sorry, this is not fixed yet. In CPO:

```
a :: {Number; String} = {1; "asd"}
```

results in an error with a line:

```
was not satisfied by the value
{"asd"; 1}
```

**Comment by mkolosick** [comment] 2017-11-24 00:44
@jpolitz: This is fixed on master. My guess is that it hasn't been deployed?

**Comment by jpolitz** [comment] 2017-11-24 19:19
It should be out in a half hour or so. I pushed this a bit ago, but due to a merge issue I didn't have time to understand, something broke, so I rolled back. I believe it's resolved now.

Sorry for the delay; I was trying to do less cherry-picking and get horizon and master/release synced up again.

**Comment by jpolitz** [comment] 2017-11-24 19:21
(I understand the merge issue now, BTW. It was that https://github.com/brownplt/code.pyret.org/pull/248 and the corresponding change in pyret-lang were out of sync; CPO ended up reporting that it couldn't find a `post-load-hooks` file.)

**Closed** 2017-12-02 04:53 UTC
Labels: type-checker
