### ISSUE TITLE
(Horizon) default modules like `lists` unbound at REPL

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#1041] opened 2017-06-20 17:25 UTC
This probably involves a tweak to module propagation in the REPL, but the builtins like `lists` are not available at the REPL even after clicking "Run" (or using `restart-interactions`).

**Comment by schanzer** [comment] 2020-03-17 14:46
`lists` are available on horizon now. Closing.

**Comment by sorawee** [comment] 2020-03-17 15:22
Wait a minute. I'm not sure what this issue is about. Is there a module value in Pyret? Also, in Horizon I evaluated `lists` in the REPL, and it is unbound, so I'm not sure what @schanzer  means by "`lists` are available on the horizon REPL now".

**Comment by schanzer** [comment] 2020-03-17 15:35
Unless I'm misunderstanding the OP, the problem is that one cannot open a new CPO window, type `lists` at the REPL, and see the various symbols exposed by that module. I can do this right now, on both horizon and CPO.

**Comment by blerner** [comment] 2020-03-17 15:51
No.  The fact that you can type `lists` and see something that looks like an object with a bunch of values on it is *mistake*, and an artifact of our original modules approach.  On the latest modules work, if you type `lists` into the REPL, it will properly complain that `lists` is not defined.  The bigger problem was that you could not type `lists.map` *in the REPL* and get a proper result, even though you could do so in the definitions area.  The intended behavior (`lists` is not defined) is available on horizon, but not yet on master.

**Closed** 2020-08-11 18:50 UTC
Labels: horizon-fixed
