### ISSUE TITLE
(typechecker) using underscore is reported as unbound id

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#711] opened 2016-05-03 04:24 UTC
```
a = _
```

results in:

```
The identifier _ is unbound. It is used but not previously defined.
```

This misleads users, as `_` can't be used as an id.

**Comment by jpolitz** [comment] 2016-06-22 14:31
Closed as duplicate of #742 742

**Closed by jpolitz** 2016-06-22 14:31 UTC
