### ISSUE TITLE
Type checker complains about tuples examples (horizon)

### ISSUE THREAD

**Issue by hilmar-hoffmann** [brownplt/pyret-lang#809] opened 2016-07-31 23:59 UTC
Link to the [tuples examples file](https://pyret-horizon.herokuapp.com/editor#share=0B4eAwTi304XcanAwR3BjaWpWeFk)

**Type check result**
![tuples-examples-type-check](https://cloud.githubusercontent.com/assets/7022324/17280209/a5686018-578a-11e6-81f2-221e8e071d19.PNG)

**Comment by jpolitz** [comment] 2016-08-01 00:00
And rightfully so!  It can tell statically that the tuple index position is out of range, so it warns you.

If you comment out that line, the whole rest of the file should happily type-check.

There's a question for a separate thread about how to write tests for dynamic errors that are caught by the type-checker...

**Comment by hilmar-hoffmann** [comment] 2016-08-01 00:21
Actually it was my main intention, to raise awareness to this kind of error. 
If a test case checks for a `raise` , it maybe should be ignored for type-checking or handled differently?
(less important, I also wanted to show the missing gap in the error message: "index3" :-))

**Comment by Heimdell** [comment] 2016-08-01 11:51
Does it allow `tuple.{a}` or `{1}` is a single literal?

**Comment by blerner** [comment] 2016-08-01 11:56
The 1 in `my-tuple.{1}` must be a numeric literal, not an identifier. Tuples are good for heterogenous, fixed size collections of values, so it's pretty hard to imagine a scenario where variable access to tuple fields is well typed and useful. In cases where you have variable length, homogenous values, you're probably better off using a list instead.

**Comment by mkolosick** [comment] 2016-08-31 18:07
I'm going to close this issue, as this is the intended behavior.

**Closed by mkolosick** 2016-08-31 18:07 UTC
