### ISSUE TITLE
Add a display hook so that rich values can be printed

### ISSUE THREAD

**Issue by melloc** [brownplt/pyret-lang#179] opened 2014-05-27 21:41 UTC
At the moment, rich values like images cannot be printed to the console. For example, something like the following code should print an image:

``` pyret
  import image as i

  my-circle = i.circle(30, "solid", "red")
  print(my-circle)
```

**Comment by jpolitz** [comment] 2015-06-04 18:38
This works on horizon now naturally with print()

**Comment by blerner** [comment] 2016-01-28 05:26
Um, no, it doesn't.  Print always produces a string output, so this produces the string `"<image (60x60)>"`.  But evaluating `my-circle` in the repl does render the circle.  I don't think we want `print` to produce rich output, though we may want another, new function that does.  (There are other issues filed that address similar things.)

**Comment by schanzer** [comment] 2016-07-14 12:32
Currently on horizon:
![image](https://cloud.githubusercontent.com/assets/77126/16839523/82b17582-499d-11e6-90f5-c91bf0ad6b52.png)

**Comment by blerner** [comment] 2016-07-14 12:38
This is expected behavior, to a point. If your program were `print("Hello")`, you'd see `Hello` followed by `"Hello"`.  The first one is the `tostring`-form of the value you're printing, and the second is the traced result of the return value of `print`, which is closer to `torepr` in behavior.  That's why you see `<internal value>` followed by a pretty picture: it's _not_ because `print` now knows how to rich-render pictures.

As for why it's `<internal value>` now instead of `<image (60x60)>`, we made that change when we moved the image library from pyret-lang into CPO...but I'm not sure whether I like the result.  In any case, the _original_ motivation of this bug report is still valid: there's no function you can use from Pyret that will rich-render values into the REPL.

**Comment by jpolitz** [comment] 2016-07-14 12:39
Yup, this is what `spy` is for, which got pushed for this release since it wasn't necessary for any summer users.  Marking unfixed and leaving open.

**Comment by blerner** [comment] 2017-08-22 14:25
Close now that spies have merged?

**Comment by jpolitz** [comment] 2017-08-24 16:26
Hooray for closing 3yo bugs! Let's leave it horizon-fixed until it's on master.

**Comment by schanzer** [comment] 2017-11-04 02:21
Closing now that this is on CPO

**Closed by schanzer** 2017-11-04 02:21 UTC
