### ISSUE TITLE
Type Parameters Not Dynamically Checked

### ISSUE THREAD

**Issue by belph** [brownplt/pyret-lang#579] opened 2015-10-15 04:28 UTC
The following typechecks and runs correctly both on code.pyret.org and pyret-horizon, even though it shouldn't:

```
fun len(lst :: List<Number>) -> Number:
  cases(List) lst:
    | link(fst,rst) => 1 + len(rst)
    | empty => 0
  end
where:
  len([list: 1, 2]) is 2
  len([list: 1, "foo"]) is 2
  len([list: "foo", 1]) is 2
end
```

This is just one example I whipped up to illustrate a number of places I've noticed type parameters not being enforced. I believe this is also related to #574 and #578.

**Comment by jpolitz** [comment] 2015-10-15 14:59
Type parameters aren't dynamically checked.  This isn't as in-your-face documented as it should be, and it only shows up in various parts of tutorials, like http://papl.cs.brown.edu/2015/Programming_in_Pyret.html#%28part._s~3aparametric%29 ("...Pyret doesn't currently check that we don't mis-use parametric...").  I'm not sure what the right place to talk about annotations as such.

That said, on horizon if you select "Type-check and Run", this program will fail to type-check.  This is for a silly reason, which is that constructor syntax like `[list: 1, 2]` doesn't work with polymorphic instantation right now.  But, if we change it to explicit constructor calls:

```
fun len(lst :: List<Number>) -> Number:
  cases(List<Number>) lst:
    | link(fst,rst) => 1 + len(rst)
    | empty => 0
  end
where:
  len(link<Number>(1, link(2, empty))) is 2
  len(link<Number>(1, link<String>("foo", empty))) is 2
end
```

This correctly fails.  If the instantiation for `<String>` isn't included, it just says it doesn't have enough information to instantiate.

**Comment by belph** [comment] 2015-10-16 12:05
Ah, okay. That's significantly less alarming, then :)
Out of curiosity, are there plans for such type-checking to be done in the future?

**Comment by jpolitz** [comment] 2015-10-16 15:35
Probably only statically. Doing it dynamically without incurring a significant runtime penalty is a tricky issue, since it naively would mean walking the whole list in certain situations, adding a linear cost to otherwise sub-linear algorithms.

Other techniques, like doing the checking lazily, are an option, but we've de-prioritized them. Doing that for parametric structures feels like a likely rabbit hole for the implementation. That said, if someone tackled it in a way that didn't make the whole runtime bend to the will of dynamically checking parametric structures, it would be good to include.

**Comment by schanzer** [comment] 2016-10-07 12:42
FWIW, trying to TC this code now results in a truly bizarre internal error on both CPO and horizon. I'm pretty sure that error is a bug in and of itself.

**Comment by shriram** [comment] 2016-10-07 12:44
Confirmed:

![image](https://cloud.githubusercontent.com/assets/75030/19190197/74464bd4-8c9c-11e6-9cee-574cc582f042.png)

Also, the error message doesn't actually say _how_ to report a bug (it could so easily have provided a link to the github bug submission URL)…

**Comment by blerner** [comment] 2017-08-22 16:56
Well, now the error goes away...but the type-checker passes this program!  @mkolosick what's going on?

**Comment by mkolosick** [comment] 2017-08-31 14:05
I was apparently not digging deep enough into `where` clauses during type checking. I've fixed that in 179ab3612c769f84a719e3329fffc3d70ea4b969.

**Comment by schanzer** [comment] 2017-11-04 02:41
Now this gives a good error message. OK to close?

**Comment by blerner** [comment] 2017-11-04 02:45
Both variants of the program above give good errors.  I'm ok with closing.

**Closed by blerner** 2017-11-04 02:45 UTC
Labels: enhancement
