### ISSUE TITLE
`overlay()` buggy

### ISSUE THREAD

**Issue by user706** [brownplt/pyret-lang#1748] opened 2024-05-31 20:15 UTC
pyret's `overlay` is messed up:

```python
# pyret

overlay(
  rectangle(500, 300, "outline", "grey"),
  
  above(
    above(
      rectangle(500, 100, "solid", "black"),
      rectangle(500, 100, "solid", "red")
      ),
    rectangle(500, 100, "solid", "gold")
    )
  
  )
```

results in this ridiculous thing:

![pyret](https://github.com/brownplt/pyret-lang/assets/39215612/f7636ed7-0e40-4a0c-b6c2-49a3144c31ef)

Racket, is good:

```racket
; racket

(require 2htdp/image)
(overlay
 (rectangle 500  300 "outline" "grey")
 
 (above
  (above
   (rectangle 500 100 "solid" "black")
   (rectangle 500 100 "solid" "red")
   )
  (rectangle 500 100 "solid" "gold")
  )
 )

```

results in:

![racket](https://github.com/brownplt/pyret-lang/assets/39215612/cade3afe-2b7e-47af-9243-41b0cbee4567)

**Comment by blerner** [comment] 2024-06-01 01:03
Closing as dupe of #1576.  This is by design at the moment, neither "messed up" nor "ridiculous".  But I agree it's unexpected!  The reason has to do with how Pyret currently treats pinholes, and there are good reasons for what it currently does, and we don't yet know of a clean, consistent way to accommodate all the desired outcomes.

**Closed by blerner** 2024-06-01 01:03 UTC

**Comment by user706** [comment] 2024-06-01 02:04
Ok; but then please show me some example variants of how I can get a German flag with a grey outline around it.

Thanks

**Comment by blerner** [comment] 2024-06-01 02:05
Look at the `center-pinhole` function, and wrap your `above(...)` sub-image in it.

**Comment by user706** [comment] 2024-06-01 08:14
Seems like a design flaw.

If you mix  "bounding box-center" and "centroid"... sometime using the one, and then the other... obviously things will not always work out nicely.

Perhaps a function `centroid-pinhole` that works on some basic shapes such as triangles, would have been better (i.e. more consistent)
(I could imagine a 2nd [slightly-modified] image library, that works exactly like racket's image lib; and has an extra function `centroid-pinhole`.)
