### ISSUE TITLE
duplicate error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#882] opened 2016-10-03 21:35 UTC
```
s = [set: 1, 2, 3]

check:
  s2 = [set: 2, 3, 1]
  s is s3
end
```

This produces the error that `s3` is not bound _twice_:

![image](https://cloud.githubusercontent.com/assets/75030/19054979/1178b23a-89c2-11e6-820f-7f6bdc0b27ab.png)

Both instances point to the same `s3`.

**Comment by blerner** [comment] 2017-04-02 18:37
Ok, I think I've tracked this down.  Basically, desugaring takes the check blocks and duplicates their code: first as the check block itself, and second as the list of thunks and test cases needed to actually run the check block.  Checking for unbound ids and bad assignments (to non-`var` ids) happens *after* that, so the unbound id appears twice.

I'm not sure quite what the right fix is, here.  Checking for unbound ids and bad assignments needs to happen after desugaring, because desugaring can introduce new bindings.  But that implies that it'll necessarily contain the duplicated code.  @jpolitz what's your take on this?

**Comment by blerner** [comment] 2017-04-02 18:37
(Note, this affects #880 too, and I think it explains the two errors we're seeing.)

**Comment by blerner** [comment] 2017-06-18 05:25
From Joe, in #618: "Pretty sure I caused this as a regression with 9a6ca6a, which doesn't omit check blocks, and ends up with those terms in two places as a result. This will actually only happen for unbound identifiers, I believe. Thanks!"

**Comment by blerner** [comment] 2018-06-28 21:06
This appears to be fixed on CPO now, too.  Closing.

**Closed by blerner** 2018-06-28 21:06 UTC
