### ISSUE TITLE
lin-reg-2V is in docs for statistics module, but is unbound after include

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1065] opened 2017-07-03 16:48 UTC
One of my students was looking for it -- do I just tell him to hold off for now?

**Comment by schanzer** [comment] 2017-07-03 17:20
I spoke with @SDooman about this on Slack. It looks like it's been removed, and replaced with a few functions that break out the statmodel functionality:

`linear-regression : List<Number> List<Number> -> (Number->Number)`
`r-squared : List<Number> List<Number> (Number->Number) -> Number`
etc.

**Comment by schanzer** [comment] 2017-11-04 03:08
Since it's been removed, I'm closing.

**Closed by schanzer** 2017-11-04 03:08 UTC
