### ISSUE TITLE
Empty data: blocks lead to bad error messages

### ISSUE THREAD

**Issue by schanzer** [brownplt/pyret-lang#865] opened 2016-09-09 11:32 UTC
`data Foo: 
end`

Results in:
![image](https://cloud.githubusercontent.com/assets/77126/18385591/9148d9a2-765f-11e6-9917-c819dd3b1261.png)

**Comment by sorawee** [comment] 2016-09-09 22:49
Oh wait, I just reported #867... Anyway, I don't think that this is an error message issue. It actually shouldn't be an error at all.

**Comment by sorawee** [comment] 2017-03-06 03:22
Duplicate of #986. Close this one as discussions are on that issue.

**Closed by sorawee** 2017-03-06 03:22 UTC
Labels: error-message
