### ISSUE TITLE
error and scrolling

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1111] opened 2017-07-31 14:19 UTC
Suppose the interactions prompt is at the bottom of the screen. Type
```
8 + 5 - 2
```
You get an error that goes below the bottom of the screen, but the screen doesn't scroll, so half the error is cut off _and_ the cursor is secretly at a prompt you can't see.

**Comment by blerner** [comment] 2017-07-31 14:23
Dupe of #964

**Closed by blerner** 2017-07-31 14:23 UTC
