### ISSUE TITLE
Need magic method for different type of equality

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#605] opened 2015-11-27 10:51 UTC
Right now we can only implement method `_equals` which will implement `==`. However, this leads to incoherence with the rest of the language. For example, I wouldn't expect the following:

```
> [SD.mutable-string-dict: "a", "b"] == [SD.mutable-string-dict: "a", "b"]
true
```

**Comment by jpolitz** [comment] 2015-11-27 14:09
More or less a dupe of https://github.com/brownplt/pyret-lang/issues/367

**Closed** 2015-11-27 18:12 UTC
