### ISSUE TITLE
click targets for test report blocks are bizarre (and broken)

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1162] opened 2017-09-08 02:52 UTC
Here's a test output:

![image](https://user-images.githubusercontent.com/75030/30194036-d6a9922e-941e-11e7-8ea3-629bd35aa057.png)

Where might one expect to click? I would think just about anywhere in this block: is there any good reason any part of it is _not_ clickable?

For whatever reason, the second line (w/ italicized text) is not clickable at all. But at least the first line is. Except _one_ part of the first line is not: the part that says "check-block-1" and is _underlined_, i.e., the part that uses the universal cue of "click here" (even though the cursor over it has a hand icon). There appears to be a tiny target region just above that text that is clickable, at least sometimes; but not clicking on it directly.

**Comment by blerner** [comment] 2017-09-08 11:31
Dupe of #601 -- this has been around for ages, and needs fixing.

**Closed** 2017-09-08 11:32 UTC

**Comment by jswrenn** [comment] 2017-09-08 13:25
Duplicate of https://github.com/brownplt/pyret-lang/issues/913.
