### ISSUE TITLE
how to write top-level contract with type variables?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1193] opened 2017-09-24 18:26 UTC
Based on https://www.pyret.org/docs/latest/s_contracts.html I can't figure out how to do this. For instance:
```
my-filter<T> :: List<T>, (T -> Boolean) -> List<T>
```

**Comment by blerner** [comment] 2018-07-02 17:10
Dupe of #1339 which will be fixed shortly.

**Closed by blerner** 2018-07-02 17:10 UTC
