### ISSUE TITLE
Confusing error message for table methods called with wrong arg count 

### ISSUE THREAD

**Issue by kfisler** [brownplt/pyret-lang#1516] opened 2020-07-15 16:32 UTC
See screenshot. The text says "3 arguments", but only two are highlighted.  I presume this is happening because the method notation is sugar for the function-call one, but it is still confusing.

(As for why would anyone write this? They were trying to figure out how to compose filter operations)

<img width="634" alt="Screen Shot 2020-07-15 at 12 25 53 PM" src="https://user-images.githubusercontent.com/1503177/87570665-f968a400-c696-11ea-929b-c8248e582798.png">

Source is in https://code.pyret.org/editor#share=1c_9b0m-yIxzHylNz7Od6lFO1_ciayUUf&v=ebd213d if needed

**Comment by blerner** [comment] 2020-07-15 16:39
Dupe of #1004 and #768

**Closed** 2020-07-15 16:39 UTC
