### ISSUE TITLE
REPL bindings are added to the environment as builtins

### ISSUE THREAD

**Issue by jpolitz** [brownplt/pyret-lang#190] opened 2014-05-29 20:06 UTC
This causes the error messages to say that, e.g., the user defined a Pyret-defined value when in fact they tried to override their own.

**Comment by schanzer** [comment] 2020-03-17 03:24
@jpolitz still an issue?

**Comment by schanzer** [comment] 2020-08-12 18:18
This is a duplicate of #665, which was fixed. Closing this one as well.

**Closed by schanzer** 2020-08-12 18:18 UTC
