### ISSUE TITLE
Confusing roughnum in error message

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#773] opened 2016-07-22 06:48 UTC
<img width="620" alt="screen shot 2016-07-21 at 23 45 23" src="https://cloud.githubusercontent.com/assets/9099577/17048772/5e89c406-4f9d-11e6-8d8e-bf664bf5ee09.png">

So somehow we have ~3.3333333333333332 evaluated to ~3.333333333333333...

**Comment by jpolitz** [comment] 2016-07-22 13:11
Life with floating points.  The console agrees:

<img width="162" alt="screen shot 2016-07-22 at 7 10 58 am" src="https://cloud.githubusercontent.com/assets/119891/17058079/81a77d0a-4fdb-11e6-83e3-7798da8ce38b.png">

Not sure much can be done about this one, other than warning when literal roughnums aren't representable, but that's sort of the point of roughnums.

**Comment by jpolitz** [comment] 2016-07-23 00:30
Closing as not a bug, so wont fix.  Any objections?

**Closed by jpolitz** 2016-07-23 00:30 UTC
