### ISSUE TITLE
table imports a bit off?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#908] opened 2016-10-22 19:50 UTC
In response to section 2 of this problem set [http://cs.brown.edu/courses/cs019/2016/tables-2tables-2.html], a student reports:

«
I opened the Plundr Spreadsheet in Google Sheets out of curiosity, and noticed that the column "Followers" precedes the column "Following," unlike in the imported Pyret table, where "Following" precedes "Followers." 

Pyret table: http://image.prntscr.com/image/b0cb0c56145e4538bac53988dfaa381f.png

Google Sheet: http://image.prntscr.com/image/ccb323b4b1ff40d7bb9e1e265baf155a.png
 »

**Comment by jpolitz** [comment] 2016-10-24 15:37
Looking at the stencil:

https://code.pyret.org/editor#share=0B0rGLk0FAgxbNElGTlpCX2x2czQ&v=6d3cfa8

It looks like the table load simply lists the names in a different order than the sheet has them.

(Also, I sent this via email two days ago, right after the issue was posted, and Github didn't register it)

**Comment by jpolitz** [comment] 2016-10-25 18:48
Looks at the stencil:

https://code.pyret.org/editor#share=0B0rGLk0FAgxbNElGTlpCX2x2czQ&v=6d3cfa8

It looks like the table load simply lists the names in a different order
than the sheet has them.

On Sat, Oct 22, 2016 at 3:50 PM Shriram Krishnamurthi <
notifications@github.com> wrote:

In response to section 2 of this problem set [
http://cs.brown.edu/courses/cs019/2016/tables-2tables-2.html], a student
reports:

«
I opened the Plundr Spreadsheet in Google Sheets out of curiosity, and
noticed that the column "Followers" precedes the column "Following," unlike
in the imported Pyret table, where "Following" precedes "Followers."

Pyret table:
http://image.prntscr.com/image/b0cb0c56145e4538bac53988dfaa381f.png

Google Sheet:
http://image.prntscr.com/image/ccb323b4b1ff40d7bb9e1e265baf155a.png
»

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/brownplt/pyret-lang/issues/908>, or mute the thread

**Comment by jpolitz** [comment] 2018-07-02 16:55
Closing as working as intended (the Pyret program can load columns with any names it chooses, this is a “bug” in the stencil.

**Closed by jpolitz** 2018-07-02 16:55 UTC
Labels: tables
