### ISSUE TITLE
is-... predicates cannot distinguish different constructors with the same name

### ISSUE THREAD

**Issue by sorawee** [brownplt/pyret-lang#591] opened 2015-10-25 17:55 UTC
```
> import ... as C
> import ... as D # where C and D are in different locations but have same code
> D.unbound-id-err("x") == C.unbound-id-err("x")
false
> C.is-unbound-id-err(D.unbound-id-err("x"))
true
```

**Comment by blerner** [comment] 2016-01-28 04:52
This appears to be a regression from when I streamlined how frequently gensyming happened in anf-loop-compiler.  Looks like I missed a step in freshening the pseudo-brands we use for data constructors.  (We don't generate actual real brander objects, because we don't need to use the branders in any first-class way; we just need a unique name for each constructor.)  The bug is likely to be at https://github.com/brownplt/pyret-lang/blob/master/src/arr/compiler/anf-loop-compiler.arr#L1128, where I think I need to call `fresh-id` too.  I'll look into this once new-horizon has landed, and we have a stable baseline again...

**Comment by blerner** [comment] 2016-01-28 18:53
Oh wait...this may be a harder than I thought.  If the two imported files have identical code, then freshening anything won't make a difference: they'll get the same gensym values.

So maybe the right solution here, I think, is either actually to get rid of the pseudo-brands we have and replace them with real ones, or to have the `is-*` checkers also check the datatype brand...but that seems more expensive than the first approach.  @jpolitz , thoughts?  Dunno if this impacts our module plans at all (it shouldn't), but it is a weird corner case of separate compilation (which definitely ties into the module stuff).

**Comment by jpolitz** [comment] 2016-01-29 15:31
There is a related modules problem, which is that if modules currently have _identical_ code, they will get cached on runtime with the same gensym'd names.  It's worth making sure that the modules themselves have  URI-based names for caching on runtime, so that two modules with the same _Pyret_ code, but in different logical locations (and thus different logical modules, since Pyret's notion of module identity is based on URI), actually are treated as separate modules.

**Closed** 2016-07-13 02:19 UTC
Labels: horizon-fixed
