### ISSUE TITLE
Non-existence of checks shows as green

### ISSUE THREAD

**Issue by david476** [brownplt/pyret-lang#1405] opened 2018-09-16 15:45 UTC
It seems like if you wrote a `where` block you probably intended to put tests in it. I just wrote an automated test for a function but forgot to put a final `is true` at the end; my code "Looks shipshape" and everything is green even though my function isn't implemented properly.

**Comment by blerner** [comment] 2019-07-17 21:24
Do we want to handle this as a well-formedness error, or just make the UI show these empty blocks as yellow?  (Well-formedness errors will prevent the program from even running, so that's a bit harsher than just making things not be green.)

**Comment by blerner** [comment] 2019-07-17 23:17
This is a dupe of #1231 - closing here since there's more discussion there.

**Closed by blerner** 2019-07-17 23:17 UTC
