### ISSUE TITLE
Problem with loading programs from google docs

### ISSUE THREAD

**Issue by rrshaban** [brownplt/pyret-lang#425] opened 2015-01-21 14:36 UTC
I saved a pyret program yesterday in lab, and it appears in my google drive but not under "My Programs" when I go to code.pyret.org. When I try to right-click open it from gdrive, I get a scary red "The program failed to load." 

What's going on?

**Comment by rrshaban** [comment] 2015-01-21 14:48
I am also now unable to connect with gDrive - I figured out that it was connected with my gDrive under SwatMail, so I deleted the app perms in gDrive for SwatMail, and am now trying to connect it with my gmail but it is not letting me "Connect to Drive" - when I click it, it flashes open a new window which quickly disappears. Clearing my cache fixes this, but then when I try to reconnect to gDrive it doesn't recognize the old code.pyret.org folder but instead creates a new one. I moved the docs from the old to the new as a workaround.

**Comment by jpolitz** [comment] 2015-01-21 20:42
@rrshaban came by and we resolved this particular case by clearing cookies, but didn't track down the underlying problem.

It is probably related to having, and switching between, multiple Google accounts.  I suspect the issue is that there was a Pyret cookie referencing a Google account that wasn't the default that was chosen with 
Connect to Drive.  But I can't reproduce it yet.

**Comment by schanzer** [comment] 2017-06-09 22:01
I know the login codepath has gotten plenty of attention since Jan 2015 - is this worth keeping open, or are there (a) other issues that are more current or (b) reasons to close this since we can't replicate anyway?

**Comment by Emmay** [comment] 2018-02-02 20:30
Same questions as above- is this issue closable now?

**Comment by schanzer** [comment] 2020-03-17 13:54
It's been 5 years we aren't seeing similar problems, even though our user base has grown a lot. I'm going to close this.

**Closed by schanzer** 2020-03-17 13:54 UTC
