### ISSUE TITLE
REPL outputs should refer back to input expressions

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#1456] opened 2019-07-13 21:57 UTC
When the definitions pane has lots of expressions, it can be really hard to figure out which output came from which expression: one has to count, and if you get it wrong, it can lead to painful debugging. Having to comment out expressions to avoid the outputs (as I sometimes do) points to a problem with the UX.

@jpolitz pointed out we're already using `spy`, so the information of the corresponding expression that was evaluated is already there. It would be nice to present that information to the user somehow. It's tricky because we already have other UI interactions on values (e.g., clicking to switch between presentation modes). Joe's suggestion was that either the values could have a little button on the right that clicking/hovering would highlight the corresponding input, or there could be something in the gutter on the left. (I suppose "both" is also an option.)

While there may be vastly greater UIs one could build (e.g., eliminate the difference between definitions and interactions, go full Bret Victor, etc.), I'd rather we not let the quest for an ideal future prevent us from doing something relatively quick and pragmatic now to address an existing pain. (This same problem also exists in DrRacket, and I've experienced it there too.)

**Comment by blerner** [comment] 2019-07-13 22:07
This is more properly a CPO issue than a pyret-lang issue, right?

Fortunately, the plumbing needed for this is already in place: https://github.com/brownplt/code.pyret.org/blob/horizon/src/web/js/repl-ui.js#L712-L735 is the relevant hook, and it already receives `loc` as a parameter.  Someone could easily tweak this output to produce different markup as desired.

**Comment by blerner** [comment] 2019-07-17 23:22
Dupe of #1201

**Closed by blerner** 2019-07-17 23:22 UTC
Labels: Good First Issue
