### ISSUE TITLE
Weird use of “annotation” in destructuring binding

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#818] opened 2016-08-03 19:07 UTC
```
fun f(p):
  {x; y} = p
  x + y
end

f(3)
```

The error says
“The annotation `{x; y}` was not…”

I don't think of the `{x; y}` as having been an _annotation_. (I mean, _I_ can see why it might be one, but I bet the typical user has no idea what “annotation” is here.)

**Comment by schanzer** [comment] 2016-08-03 19:58
This seems similar to some of the slack discussion on error messages, where the vocabulary in the error message assumes a greater understanding on the part of the user.

**Comment by jswrenn** [comment] 2016-08-03 21:35
This appears to be a recent regression; the error message you get on the master branch is more on point:
![screenshot-code pyret org 2016-08-03 17-31-43](https://cloud.githubusercontent.com/assets/3820879/17382699/30b11f90-59a0-11e6-8bd3-25e49f102946.png)

This was probably introduced by changes in the desugaring of tuple destructuring-bindings.

**Comment by blerner** [comment] 2016-08-03 21:59
True, but incorrect diagnosis.  The reason master gives you that behavior is because it does not permit arbitrary tuple bindings, and uses a simpler, and more limited, desugaring.  When I added tuple-bindings-everywhere, we generate better annotations and better bindings, for earlier warning of errors.  Hence the annotation error.

**Comment by blerner** [comment] 2016-08-03 22:41
Specifically, the annotations generated at https://github.com/brownplt/pyret-lang/blob/sql/src/arr/compiler/resolve-scope.arr#L154 and https://github.com/brownplt/pyret-lang/blob/sql/src/arr/compiler/resolve-scope.arr#L165, which are generated both to help the typechecker know when things are supposed to be tuples, and also to fail faster at runtime and give earlier error messages.  The problem is, when these annotations are synthesized, there's no good srcloc to pin them to.

**Comment by blerner** [comment] 2019-07-17 23:56
This now produces
![image](https://user-images.githubusercontent.com/918464/61419609-0066a600-a8cd-11e9-875b-b176460664c5.png)

Closing.

**Closed by blerner** 2019-07-17 23:56 UTC
